version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    volumes:
      - ./server/src:/app/server/src
    command: ts-node-dev --respawn --pretty --transpile-only index.ts
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    depends_on:
      - server
    command: npm run start
    restart: always